# Imports and Functions

In [1]:
import pandas as pd
from pathlib import Path
from importlib import reload
import data_loading  # Import the module instead of specific functions


reload(data_loading)  # Reload the module after making changes

# Now you can reference the functions directly from the reloaded module
read_csv_to_dataframe = data_loading.read_csv_to_dataframe
read_txt_to_dataframe = data_loading.read_txt_to_dataframe

/Users/cameronmackinnon/PD/Winter 2024 Job Hunt/Companies/Validere/crude_oil_accidents/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Load in Dataset B

In [2]:
## making file path imports more robust

# get directory of current file
current_script_directory = Path.cwd()

# Construct path to data files given relative location
cad_string = current_script_directory / "../data/raw/canada/"
cad_data_2 = cad_string / "PODSdb_MDOTW_VW_OCCURRENCE_PUBLIC.csv"

# read data into dataframes
cad_data_2_raw = read_csv_to_dataframe(cad_data_2)

File at '/Users/cameronmackinnon/PD/Winter 2024 Job Hunt/Companies/Validere/crude_oil_accidents/src/../data/raw/canada/PODSdb_MDOTW_VW_OCCURRENCE_PUBLIC.csv' successfully read into a DataFrame.

# Cleaning

In [3]:
clean_df = cad_data_2_raw.copy()

## looking for substance carried
clean_df.loc[clean_df['productcarriedid_displayeng']!=clean_df['productreleaseddisplayeng']][['productcarriedid_displayeng', 'productreleaseddisplayeng']].drop_duplicates()

     productcarriedid_displayeng productreleaseddisplayeng
26                           NaN                       NaN
147               Other - Liquid                       NaN
455                    Crude Oil                       NaN
669             Refined Products                       NaN
1393                 Natural Gas                       NaN
1756                  Condensate                       NaN
1813                    Sour Gas                       NaN
1833   Natural Gas Liquids / LPG                       NaN

In [4]:
## based on the above we can just use productcarriedid_displayeng. let's also drop any rows where it is n/a as they are not useful.
clean_df = clean_df.loc[clean_df['productcarriedid_displayeng'].isna()==False]

clean_df.groupby(['productcarriedid_displayeng']).count()

,occno,occid,occclassid,occclassid_displayeng,occclassid_displayfre,occtypeid,occtypeid_displayeng,occtypeid_displayfre,occdate,occtime,...,notification_details_provinceid,notification_details_provinceid_displayeng,notification_details_provinceid_displayfre,tsbnotifiednebdate,tsbnotifiednebtime,dateofcall,timeofcall,totalseriousinjuries,totalfatalinjuries,dailyreleaseddate
productcarriedid_displayeng,,,,,,,,,,,,,,,,,,,,,
Acid Gas,6,6,6,6,6,6,6,6,6,6,...,0,0,0,6,6,0,0,6,6,6
Condensate,56,56,56,56,56,56,56,56,56,37,...,8,8,8,28,24,1,1,56,56,56
Crude Oil,859,859,859,859,859,859,859,859,859,703,...,87,87,87,469,478,21,21,859,859,858
Crude Oil-Sour,2,2,2,2,2,2,2,2,2,2,...,0,0,0,1,1,0,0,2,2,2
Liquefied Petroleum Gas,30,30,30,30,30,30,30,30,30,16,...,0,0,0,12,12,0,0,30,30,30
Natural Gas,1103,1103,1103,1103,1103,1103,1103,1103,1103,1008,...,334,334,334,522,534,37,37,1103,1103,1092
Natural Gas Liquids / LPG,135,135,135,135,135,135,135,135,135,127,...,11,11,11,76,76,2,2,135,135,134
Other,280,280,280,280,280,280,280,280,280,221,...,0,0,0,183,193,0,0,280,280,280
Other - Gas,3,3,3,3,3,3,3,3,3,3,...,0,0,0,1,1,0,0,3,3,3
Other - Liquid,30,30,30,30,30,30,30,30,30,30,...,15,15,15,8,8,4,4,30,30,30
Refined Products,155,155,155,155,155,155,155,155,155,115,...,15,15,15,29,32,1,1,155,155,155
Sour Gas,140,140,140,140,140,140,140,140,140,127,...,11,11,11,83,85,8,8,140,140,139

In [16]:
## SHOOT - ONLY 2 ROWS where we have sour. let's move on to another dataset. 
clean_df.loc[clean_df['productcarriedid_displayeng']=='Crude Oil-Sour']

,occno,occid,occclassid,occclassid_displayeng,occclassid_displayfre,occtypeid,occtypeid_displayeng,occtypeid_displayfre,occdate,occtime,...,notification_details_provinceid,notification_details_provinceid_displayeng,notification_details_provinceid_displayfre,tsbnotifiednebdate,tsbnotifiednebtime,dateofcall,timeofcall,totalseriousinjuries,totalfatalinjuries,dailyreleaseddate
1272,P13H0011,96047,9,5,5,3,INCIDENT,INCIDENT,2/2/2013 12:00:00 AM,10:30:00,...,NaN,NaN,NaN,2/2/2013 12:00:00 AM,13:10:00,NaN,NaN,0,0,9/25/2017 12:00:00 AM
1571,P15H0098,96407,9,5,5,3,INCIDENT,INCIDENT,10/15/2015 12:00:00 AM,9:15:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,9/25/2017 12:00:00 AM